---
repos:
  # Meta hooks: https://pre-commit.com/#meta-hooks
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes

  # See https://pre-commit.com for more information
  # See https://pre-commit.com/hooks.html for more hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-case-conflict

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: script-must-have-extension
          - id: shellcheck
          - id: shfmt
            args: [-i 2, -ci, -bn, -sr]
